IBM/ibm-spectrum-scale-csi

driver/cmd/ibm-spectrum-scale-csi/main.go, driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs.go, driver/csiplugin/gpfs_util.go, go.mod
* driver can now build manually again
* driver can now lint manually again
=> fix module imports on driver

README.driver.md, driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/resources.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs.go, driver/csiplugin/gpfs_util.go
Merge IBM/ibm-spectrum-scale-csi-driver#66 and IBM/ibm-spectrum-scale-csi-driver#67
> these were ongoing work that happened while combining repositories
=> Merge IBM/ibm-spectrum-scale-csi-driver#66 and IBM/ibm-spectrum-scale-csi-driver#67

operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml, operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.0.1/ibm-spectrum-scale-csi-operator.v1.0.1.clusterserviceversion.yaml
Resolves #61 
I didn't make the  changes to the 1.0.0 clusterservice yamls file, figured we should leave those for historic reasons. 
Let's see if the Travis Complains or not.
=> Updating the 1.0.1 yaml file to change : to - in the WARNING string

.travis.yml
=> Add quay.io expiration for nightly operator images

operator/molecule/default/tests/basic_tests.yaml, operator/molecule/default/tests/test_creation.yaml, operator/molecule/default/tests/test_secrets.yaml, operator/roles/csi-scale/tasks/cluster_check.yml, operator/roles/csi-scale/tasks/main.yml
Fixes a bug  in which the operator would get stuck if the secret wasn't defined ahead of time.
=> Secret Fix - undefined

operator/deploy/crds/csiscaleoperators.csi.ibm.com.cr.yaml
Added node mapping format details in cr yaml for k8s node which start with number
=> node mapping details in cr yaml

README.md, operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.1.0/ibm-spectrum-scale-csi-operator.v1.1.0.clusterserviceversion.yaml
Fixes #114 
* Adds links to KC
* Re-targets old links
* Adds a support statement to the README
=> Documentation enhancements

driver/csiplugin/gpfs.go
=> driver parameter validation error message improvement

driver/csiplugin/gpfs.go, operator/deploy/crds/csiscaleoperators.csi.ibm.com.cr.yaml
=> Make primaryFset optional

driver/csiplugin/gpfs.go, driver/csiplugin/settings/scale_config.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/deploy/crds/csiscaleoperators.csi.ibm.com.cr.yaml, operator/deploy/crds/csiscaleoperators.csi.ibm.com.crd.yaml
=> Derive the RemoteFs internally

tests/functional-tests/.pylintrc, tests/functional-tests/README.md, tests/functional-tests/config.json, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/pytest.ini, tests/functional-tests/requirements.txt, tests/functional-tests/scale_operator.py, tests/functional-tests/setup.cfg, tests/functional-tests/utils/.pylintrc, tests/functional-tests/utils/crd_properties.json, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/namegenerator.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py
Initial code of Functional Test Automation Suite which should be exercised IBM Spectrum Scale CSI driver & operator functionality.
High Level Supported Features (Total 320+ Test cases )
CSI Driver Test Automation Support
---------------------------------------
1. Static provisioning 
Ability to use existing directories as persistent volumes
2. Lightweight dynamic provisioning 
Ability to create directory based volumes dynamically
3. Fileset based dynamic provisioning 
Ability to create fileset based volumes dynamically
3.1 Independent  Fileset 
3.2 Dependent Fileset
CSI Operator Test Automation Support
---------------------------------------
1. Different values for Customer Object configuration 
Ability to deploy operator with different values in Custom Resource object deployment
2. …
=> functional tests for IBM spectrum scale CSI driver & operator using pytest framework

tools/spectrum-scale-driver-snap.sh
fixes #159 
Handle case where during upgrade there might be more than one operator pod running.
=> Handle multiple operator pod in snap

driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs_util.go
=> Fix for failure during remote pvc creation

operator/roles/csi-scale/tasks/secret_watch.yml
Closes #187
Removes debug  log.
=> Remove secret debug  from  log.

operator/roles/csi-scale/tasks/clear_old_csi_access.yml, operator/roles/csi-scale/tasks/main.yml
Fixed the removal logic on the SCC upgrade. Tested in an OCP environment.
=> Removes old SCC on upgrade

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, tools/ansible/generate/create_files.yaml
1. Sets image pull policy  to  `Always`.
2. Sets image version to `dev`.
=> Modifying -dev generated  yaml file to match spec requested in #176

tools/spectrum-scale-driver-snap.sh
Signed-off-by: Micky Yun Chan <michan@redhat.com>
Closes #144
---
The old PR got super stale and should have been merged months ago.
=> Add Daemonset descibe in snapshot tool

operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml
This should fix the indentation issue.
Closes #185
=> Fix for CR indentation

tests/functional-tests/README.md, tests/functional-tests/utils/scale_operator_function.py
readme update and release version change
NA
NA
NA
NA
=> readme update and release version change

tools/spectrum-scale-driver-snap.sh
Changes the pod log aggregator to use labels instead of pod name.
Ran snapshot tool to see if pods with correct labels were gathered.
N/A
N/A
Fixes #196
=> Generalizing snapshotting

Makefile, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/files/manifest.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/files/manifest.yaml, docs/source/conf.py, docs/source/developers/clone.rst, driver/build/Dockerfile, driver/build/multi-arch.Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/build/Dockerfile, operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml, operator/deploy/operator.yaml, operator/roles/csi-scale/defaults/main.yml, tools/ansible/cert-playbook.yaml, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml, tools/ansible/olm-test-playbook.yaml, tools/ansible/versioning-playbook.yaml
Operator and driver version bumped to 2.0.0
N/A
N/A
N/A
N/A
=> Bumping to 2.0.0 for operator.

tests/functional-tests/README.md, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/scale_operator_object_function.py
Remote cluster Test cases enhancements and minor fixes
NA
NA
NA
=> Remote cluster Test cases enhancements and minor fixes

operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/2.0.0/ibm-spectrum-scale-csi-operator.v2.0.0.clusterserviceversion.yaml
1.1.0 => 2.0.0 in images 
N/A
N/A
OLM should work
N/A
=> Fixing image pointed to by CSV.

docs/source/developers/olm.rst, operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml, operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/2.0.0/ibm-spectrum-scale-csi-operator.v2.0.0.clusterserviceversion.yaml, tools/ansible/olm-test/check-version-play.yaml, tools/ansible/olm-test/oc-sub.yaml.j2
* Added fresh documentation to the CSV, based on #227, bumped the create date to match.
* Added a courier check for the  OLM playbook.
Ran an olm end to end demonstration with @MonicaLemay and @Jainbrt 
CSV refinements defined in  #227.
N/A
#227
=> CSV doc fixes and OLM playbook improvement

driver/csiplugin/connectors/rest_v2.go
Returning the additional error message 
Verify message being shown for various operations
NA
NA
Fixes #219
=> Printing additional error message

.travis.yml, operator/build/Dockerfile
switching to ansible-operator:v0.17.2
=> switching to ansible-operator:v0.17.2

operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/2.0.1/ibm-spectrum-scale-csi-operator.v2.0.1.clusterserviceversion.yaml
Fixing the CSV link for v2.0.1.
=> V2.0.1 link fix

tests/functional-tests/.pylintrc, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/requirements.txt, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/namegenerator.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py, tests/functional-tests/utils/snapshot.py
Changes list :
1.    Changes for CSI driver support for multifilesystem & multicluster
2.    Changes for keep kubernetes objects after the test run
3.    Tests for snapshot functionality
4.    Introduce runslow parameter for few slow running testcases 
5.    Using yaml file to create role,rolebinding and service account 
6.    Changes in requirement.txt file for min required python packages
7.    Error message changes introuduced by PR 257
=> CSI driver automation support for multifilesystem,multicluster & snapshots

operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/2.0.0/ibm-spectrum-scale-csi-operator.v2.0.0.clusterserviceversion.yaml, tools/ansible/README.md, tools/ansible/cert/verify_operator.yaml
Fixes an issue in  the CSV that screws up a link to the KC (fixed in operatorhub and redhat already).
=> Fixing the link for 2.0.0's CSV

tools/spectrum-scale-driver-snap.sh
=> snap tool update for collecting snapshot logs

tests/functional-tests/README.md, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/pytest.ini, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/requirements.txt, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py, tests/functional-tests/utils/snapshot.py
Changes:
1. Fixed the issue for creating the CRD V1 API using CR object
2. Fixed timing issue for operator test cases and error changes issues 
3. Function Documention changes
=> Change for CRD using CR update and fixes for operator test cases

tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py, tests/functional-tests/utils/snapshot.py
1. Improved run time using runslow parameter
2. Added check for restore feature available in the code
3. fix for k8s objects cleanup in snapshot testcases and error message
=> Changes for improving runtime and restore snapshot

SNAPSHOTS.md, driver/csiplugin/controllerserver.go, driver/examples/snapshots/pvcfrmsnap.yaml, driver/examples/snapshots/static_volsnap.yaml, driver/examples/snapshots/static_volsnapcontent.yaml, tools/generate_volsnapcontent_yaml.sh
- Added instructions to create static volume snapshots from existing Spectrum Scale fileset snapshots.
- Added script to generate volume snapshot content yaml
- Fixed the snapshot ID parsing.
=> Static Volume Snapshots

tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/snapshot.py
Collected scale version & k8s version information collection in get version test case
=> Collect information about scale & k8s version in the report

tests/functional-tests/README.md, tests/functional-tests/build/Dockerfile, tests/functional-tests/config/test.config, tests/functional-tests/conftest.py, tests/functional-tests/csi-test-pod.yaml, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/requirements.txt, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/scale_operator_function.py
1. Moved configuration parameter from conftest.py to test.config 
2. Build/Dockerfile for creating the csi docker test image 
3. csi test pod sample file
=> Changes for Dockerimage

tests/functional-tests/Readme.docker.md, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py
1. Readme for running tests using docker container image 
2. Changes for using default configuration path in docker container if user has not provided
3. Don't delete namespace if user has already created before running the tests
=> Readme for running tests using docker container image

tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/snapshot.py
static snapshot functions & testcases
=> Initial checkin for static snapshot functions

operator/roles/csi-scale/templates/csi-plugin.yaml.j2, operator/roles/csi-scale/templates/scc.yaml.j2
=> setting hostNetwork: true with dnsPolicy: ClusterFirstWithHostNet

tests/functional-tests/driver_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py
Update in getversion function for imageid and regression bucket for remote_test.py
=> Update in getversion function for imageid and regression bucket for remote_test.py

tools/spectrum-scale-driver-snap.sh
=> fixing the spectrum-scale-driver-snap

SNAPSHOTS.md, driver/examples/snapshots/static_volsnap.yaml, driver/examples/snapshots/static_volsnapcontent.yaml, driver/examples/snapshots/volsnap.yaml, driver/examples/snapshots/volsnapclass.yaml, tools/generate_volsnapcontent_yaml.sh
Changes in SNAPSHOTS.md for snapshotcontroller version update 
Changes in snapshot examples from v1beta1 to v1
=> changes in SNAPSHOTS.md and example update

operator/roles/csi-scale/templates/scc.yaml.j2
"hostNetwork" was set incorrectly to false during prior merge. Fixing that.
=> Fixing scc for hostNetwork

tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/cleanup_functions.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/scale_operator_function.py, tests/functional-tests/utils/scale_operator_object_function.py, tests/functional-tests/utils/snapshot.py
1. removed duplicate test test_get_version
2. changes for snapshot retore test cases working
3. static snapshot default deletion policy Retain
=> Snapshot automation test fixes

tests/functional-tests/Readme.docker.md, tests/functional-tests/scale_operator.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py
default cr.yaml path change in tests due to operator upgrade to sdk 1.3.2 
spelling correction of Logger
=> default cr.yaml path change in tests due to operator upgrade to sdk 1.3.2 

driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go
=> Verify Spectrum Scale Version for Snapshot support

operator/roles/csiscaleoperator/templates/csi-plugin.yaml.j2
Switching imagePullPolicy to Always for dev driver images
=> Switching imagePullPolicy to Always

tools/generate_volsnapcontent_yaml.sh
=> corrected SnapshotHandle for volsnapcontent

tests/functional-tests/driver_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py, tests/functional-tests/utils/fileset_functions.py, tests/functional-tests/utils/snapshot.py
1. check for 5.1.1.0 in snapshot test cases
2.  updated the snapshot test cases failure reasons 
3.  automation fix for multi attach pod
=> check for 5.1.1.0 in snapshot test cases

tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py, tests/functional-tests/utils/driver.py
snapshot tests for restore on different storageclass & nodeclass
=> snapshot tests for restore on different storageclass & nodeclass

operator/roles/csiscaleoperator/templates/csi-plugin.yaml.j2
Switching imagePullPolicy back to IfNotPresent
=> Switching imagePullPolicy back to IfNotPresent

tests/functional-tests/README.md, tests/functional-tests/Readme.docker.md
cr.yaml file path changes in readme and supported version update
=> cr.yaml file path changes in readme and supported version update

tools/spectrum-scale-driver-snap.sh
enhance log collection script to collect csi version and pod image versions
=> find out csi version and images (#425)

operator/config/samples/csi_v1_csiscaleoperator.yaml, operator/config/samples/csiscaleoperators.csi.ibm.com_cr.yaml, operator/roles/csiscaleoperator/defaults/main.yml
Sidecar upgrade
livenessprobe sidecar upgrade to 2.3.0
snapshotter sidecar upgrade to 4.1.1
provisioner sidecar upgrade to 2.2.2
attacher sidecar upgrade to 3.2.1
node-registrar sidecar upgrade to 2.2.0
=> Sidecar upgrade 

tests/functional-tests/csi-test-pod.yaml
CSI automation test pod imagepullpolicy to Always
=> CSI automation test pod imagepullpolicy to Always

tests/functional-tests/README.md, tests/functional-tests/Readme.kubernetes.md, tests/functional-tests/conftest.py, tests/functional-tests/driver_test.py, tests/functional-tests/operator_test.py, tests/functional-tests/remote_snapshot_test.py, tests/functional-tests/remote_test.py, tests/functional-tests/scale_operator.py, tests/functional-tests/snapshot_test.py
1. allow to run automation tests in any namespace
=> allow to run automation tests in any namespace

operator/roles/csiscaleoperator/templates/csi-plugin-snapshotter.yaml.j2
fixes #448 
Signed-off-by: Deepak R Ghuge <deeghuge@in.ibm.com>
=> Add missing imagePullSecret and tolerations section for snapshotter 

driver/csiplugin/controllerserver.go
as minimum required Scale version.
=> Update Scale version check in Snapshot/cloning to check v5.1.2.1

driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs.go
=> Use Sync.Map for concurrency handling in Volume Cloning

driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs.go
=> sync.Map changes to handle concurrency for snapshots

operator/controllers/syncer/csi_syncer.go
```
Added --default-fstype=gpfs parameter in CSI provisoner
```
-
-
=> Added --default-fstype=gpfs parameter in CSI provisoner

driver/go.mod, driver/go.sum
=> Using CSI spec 1.5.0

driver/build/Dockerfile, driver/build/multi-arch.Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, driver/go.mod, operator/controllers/config/constants.go, operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go
```release-notes
Bump CSI sidecar to following versions:
CSI Snapshotter -> v5.0.1
CSI Attacher ->v3.4.0
CSI Provisioner -> v3.1.0
CSI Node Driver Registrar -> 2.4.0
Livenessprobe -> 2.5.0
```
-
-
=> CSI driver sidecar version update for 2.5.0 release 

.travis.yml, driver/build/Dockerfile, operator/build/Dockerfile
=> Dockerfile update

operator/controllers/config/constants.go
```release-notes
CSISnapshotterImage -> 5.0.1 (sidecarupdate)
```
-
-
=> CSISnapshotterImage -> 5.0.1 (sidecarupdate)

.travis.yml, operator/build/Dockerfile
```release-notes
NONE
```
- operator builds x86_64 binary and copies it into multi-arch (ppc64le, s390x, etc) base image.  This causes exec format failures on those other platforms.
- Build the correct architecture
=> correct multi-arch build for operator Dockerfile

.travis.yml
=> disabling the operator package push

driver/csiplugin/controllerserver.go
- Fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/570
- Also removed CG field (added an empty string instead of CG) in volume ID for volumes created with old storage class
-
-
=> Remove quota from independent fileset for new volumes

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml
```release-notes
```
NA
Updating CSI image manifests for 21-Jan-2022 delivery
=> Updating CSI image manifests for 21-Jan-2022 delivery

driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, operator/main.go
```release-notes
NONE
```
- we do not log commit revision and it can be hard to know what code you are running
- pass COMMIT env from travis into Dockerfile and have go compile in static variable with the commit revision, which is then logged.
=> Log build commit revision in CSI driver and operator main

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml
=> Updating CSI image manifests for 01-Feb-2022 delivery

driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/settings/scale_config.go, driver/csiplugin/utils/utils.go, operator/controllers/config/constants.go
=> fixing gosec findings

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml
```release-notes
```
NA
Updating CSI image manifests for 08-Feb-2022 delivery
=> Updating CSI image manifests for 08-Feb-2022 delivery

operator/controllers/config/constants.go
```
LivenessProbeImage sidecarupdate to 2.6.0
```
-
-
=> LivenessProbeImage sidecarupdate to 2.6.0

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml
=> Updating CSI manifests for 16-Feb-2022 build

driver/csiplugin/controllerserver.go
```release-notes
```
-
Version check message didn't state the required filesystem version
-
Version check message now shows the required filesystem version in the error message
=> Add required filesystem version for tiering suport check (27.00)

driver/csiplugin/controllerserver.go
- Fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/613
- Some auto-formatting by vscode
```release-notes
```
-
-
=> Add `nodeClass` in SC supported parameters

driver/csiplugin/controllerserver.go
```release-notes
```
Snapshots failing for remote cluster with different file names
Fix for - snapshots failing for remote cluster with different file names
=> Fix for issue #627

driver/csiplugin/controllerserver.go
Added handling for for 00.00 GMT timezone as REST API returns the Z as timezone instead of format [+-]XX:XX. 
```release-notes
```
-
-
=> handle the GMT 0 timezone 

driver/csiplugin/controllerserver.go
Fix for defect #645
First Snapshot creation succeeds for CG when snapWindow is invalid. Subsequent snapshot creation fails.
Fixed the above mentioned issue.
=> Fix for defect #645

tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_storage_function.py
=> automation change for fetching cg filesetname

tests/functional-tests/ibm_spectrum_scale_csi/base_class.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_storage_function.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/kubernetes_objects_function.py, tests/functional-tests/tests/consistency_group_test.py, tests/functional-tests/tests/remotecluster_consistency_group_test.py, tests/functional-tests/tests/remotecluster_volume_snapshot.py, tests/functional-tests/tests/volume_snapshot.py
=> Fix for consistency group test automation

tests/functional-tests/ibm_spectrum_scale_csi/common_utils/input_data_functions.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_storage_function.py
=> automation test fix primaryfs change

operator/controllers/csiscaleoperator_controller.go
This pull request fixes the following issue:
- https://github.ibm.com/IBMSpectrumScale/scale-core/issues/3177
- Removing the `csiScaleOperator` resource from the cluster, was not removing the SCC resource created by the controller.
- Removing the `csiScaleOperator` resource, invokes finalizer which removes SCC resource.
=> Cleanup of SecurityContextConstraints

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/manifests/bases/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml, operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/2.5.0/ibm-spectrum-scale-csi-operator.v2.5.0.clusterserviceversion.yaml, operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/manifests/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
For CSI 2.5.0 release, switch from ICR images to quay images for operator yaml
NA
NA
=> Switching from ICR images to quay images for operator yaml

tests/functional-tests/README.md, tests/functional-tests/config/test.config, tests/functional-tests/csi-test-pod.yaml, tests/functional-tests/ibm_spectrum_scale_csi/base_class.py, tests/functional-tests/ibm_spectrum_scale_csi/common_utils/input_data_functions.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_object_function.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_storage_function.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/kubernetes_objects_function.py, tests/functional-tests/ibm_spectrum_scale_csi/spectrum_scale_apis/fileset_functions.py, tests/functional-tests/pytest.ini, tests/functional-tests/requirements.txt, tests/functional-tests/tests/conftest.py, tests/functional-tests/tests/consistency_group_snapshot_test.py, tests/functional-tests/tests/consistency_group_test.py, tests/functional-tests/tests/remotecluster_consistency_group_snapshot_test.py, tests/functional-tests/tests/remotecluster_consistency_group_test.py, tests/functional-tests/tests/remotecluster_volume_provisioning.py, tests/functional-tests/tests/remotecluster_volume_snapshot.py, tests/functional-tests/tests/volume_provisioning.py, tests/functional-tests/tests/volume_snapshot.py
```release-notes
Support for OCP/k8s Token and CACERT
Support for auto read of REST API secret 
Support for new test namespace for every new test run
Code re-usability using new fixtures
Use of upgraded version of python module dependencies.
```
-
-
=> adding token, auto secret read, test namespace creation, fixture based test initialisation, upgrading requirements in Automation

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml
CSI 4-Apr-22 image digests
NA
NA
=> CSI Image digests for 4-Apr delivery

tests/functional-tests/ibm_spectrum_scale_csi/base_class.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_object_function.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/kubernetes_objects_function.py
=> automation change for statefulset to deployment of csi sidecars

operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/2.5.1/ibm-spectrum-scale-csi-operator.v2.5.1.clusterserviceversion.yaml, operator/controllers/config/constants.go
Must go in 2.5.1
- `containerImage` in 2.5.1 CSV was having incorrect image.
- corrected the image name.
=> Fixes for 2.5.1

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml, operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/2.5.1/ibm-spectrum-scale-csi-operator.v2.5.1.clusterserviceversion.yaml, operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/manifests/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
=> Image digest update for CSI 2.5.1 release

tools/spectrum-scale-driver-snap.sh
=> spectrum-scale-driver-snap.sh tool improvements

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go, operator/controllers/syncer/csi_node.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
Change versions to 2.7.0 and also changed `SHORTNAME_NODE_MAPPING` value to `no` for CNSA kustomization.
=> Change versions to 2.7.0

tests/functional-tests/config/test.config, tests/functional-tests/ibm_spectrum_scale_csi/base_class.py, tests/functional-tests/ibm_spectrum_scale_csi/common_utils/input_data_functions.py, tests/functional-tests/ibm_spectrum_scale_csi/kubernetes_apis/csi_storage_function.py, tests/functional-tests/tests/conftest.py
Signed-off-by: vrushch <Vrushal.Chaudhari@ibm.com>
```release-notes
```
-
-
=> Adding Keepobject on failure in automation

tests/functional-tests/config/test.config, tests/functional-tests/ibm_spectrum_scale_csi/common_utils/input_data_functions.py
Signed-off-by: vrushch <Vrushal.Chaudhari@ibm.com>
```release-notes
```
-
-
=> Automation: test.config file change

operator/config/overlays/cnsa/kustomization.yaml
```release-notes
Switch CNSA node mapping to shortname
```
CNSA needs to use short names in the mapping for FQDN support
- Short name mapping not used
- Use short name mapping
=> Switch CNSA node mapping to shortname

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> 1st Sept build

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> 6th Sept build

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, operator/config/manager/manager.yaml
=> changes in manager.yaml and cloudpak

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml
=> image digest update with 2.7.0 tag

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/default/kustomization.yaml
=> Move from dev quay to production quay for 2.7.0 GA

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
=> Change versions to 2.8.0

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go
=> external-snapshotter sidecar upgrade to 6.1.0

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go, operator/controllers/syncer/csi_syncer.go
csi-attacher :  v3.4.0-> v4.0.0
csi-resizer:   v1.4.0 -> v1.6.0
csi-node-driver-registrar : v2.5.0 -> v2.5.1
```release-notes
```
-
-
=> sidecar attacher and node-registrar update

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> 4th Oct build

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/rbac/role.yaml, operator/controllers/csiscaleoperator_controller.go, operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go
Updated clusterroles for sidecars and operator
```release-notes
```
-
-
=> Updated clusterroles

operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go
Signed-off-by: ghanshyam-11 <ghanshyam.sharma1@ibm.com>
```release-notes
```
-
-
=> "Updated role verb for snapshotter"

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> 18th Oct build

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
```
Go version and Operator SDK updates
```
-
-
=> 271022 build

driver/csiplugin/gpfs.go
Fixes #821 
```release-notes
```
-
-
=> Primary fileset check after refresh task

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go
=> livenessprobe upgrade from 2.7.0->2.8.0

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/default/kustomization.yaml
=> Move to production quay for 2.8.0 GA

driver/csiplugin/controllerserver.go
=> Fix err handling

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
```release-notes
Sidecar update:
CSI Snapshotter -> 6.2.0
CSI Attacher -> 4.1.0
CSI Provisioner -> 3.4.0
CSI resizer -> 1.7.0
CSI Node Driver Registrar -> 2.7.0
Livenessprobe -> 2.9.0
Version change to 2.9.0
https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots
```
-
-
=> sidercar upgrade and version change to 2.9.0

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> Jan 13th build

driver/csiplugin/nodeserver.go
=> Handle is not found err

driver/csiplugin/nodeserver.go
=> Use symlink for GM fixpack 2

driver/csiplugin/server.go
=> functionality for csi.sock file permission

driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs.go, operator/controllers/csiscaleoperator_controller.go, operator/controllers/syncer/csi_node.go
- Get symlink dir path for volume create at driver side
- Fix a gosec issue in operator
- Handle error 403 from GUI
- Fix https://github.com/IBM/ibm-spectrum-scale-csi/issues/883
Operator passes symlink dir path to driver
Driver gets/forms symlink dir path
=> Get symlink dir path in driver

operator/controllers/csiscaleoperator_controller.go
=> Fixed redundant events in CSO

driver/cmd/ibm-spectrum-scale-csi/main.go, driver/go.mod, driver/go.sum
- This is a step 1 of a 2-step process of correcting the module dependencies for production. Once this is merged, will use the driver module from latest dev as a dependency for the operator module
=> Correct driver module

driver/csiplugin/nodeserver.go
- Added an old approach of symlink for NodePublish
- A switch for symlink Vs. bindmount - default will be bindmount
- NodePublish uses only bindmount
- NodePublish uses bindmount or symlink based on a switch (env var in configmap `ibm-spectrum-scale-csi-config`), default is bind mount
- How to use:
- VAR_DRIVER_NODEPUBLISH_METHOD=SYMLINK or BINDMOUNT in configmap `ibm-spectrum-scale-csi-config`
=> Add symlink for NodePublish + switch for symlink/bindmount

tools/generate_static_provisioning_yamls.sh
=> fixed static provisioning issues

tools/spectrum-scale-driver-snap.sh
```release-notes
Added support for option to collect previous logs or not 
Added support for option to collect logs with certain timeframe 
use - instead of : in the logs dir name
collect events form CSI driver namespace
remove duplicate output of "get pods"
```
-
-
=> improvements in csi snap tool

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, operator/config/manager/manager.yaml
=> cloudpak 2.9.0 changes

driver/csiplugin/nodeserver.go
There is an error reported while performing NodePublishVolume operation. There was error related to unmount to some fake targetPath which mount library perform to test using fake executor.
[https://github.com/kubernetes/mount-utils/blob/0660721e7712108e303e8b075c6426b7f224b855/mount_linux.go#L272](https://github.com/kubernetes/mount-utils/blob/0660721e7712108e303e8b075c6426b7f224b855/mount_linux.go#L272)
```release-notes
```
-  Currently there was initialisation of mounter which leads to failed logs related to unmount while NodePublishVolume and NodeUnPublishVolume operations.
- Changes has removed initialisation using method and now structure of mounter has been implemented, which will fix the issue related to unmount while …
=> withSafeNotMountedBehavior fix

driver/csiplugin/connectors/connectors.go, driver/csiplugin/gpfs.go, driver/csiplugin/identityserver.go, driver/csiplugin/nodeserver.go, driver/csiplugin/server.go, driver/csiplugin/utils.go
fixing log message of node server and identity server
```release-notes
```
-
-
=> fixing log message of nodeserver

driver/build/Dockerfile
Image: quay.io/amdabhad/csi-driver:ubi9
=> Move to ubi9

driver/csiplugin/controllerserver.go
Zenhub issue tracker:- [Code refactoring of CreateVolume functionality](https://github.ibm.com/IBMSpectrumScale/csi-tracker/issues/300)
```release-notes
```
-
-
=> create volume code refactor

driver/csiplugin/nodeserver.go
Serialize NodePublish and NodeUnpublish so that even when multiple parallel requests come at the same time, only one of them is processed at a time ensuring the atomic operation.
When there are multiple NodePublish/NodeUnpublish requests, they can run in parallel at a time
When there are multiple NodePublish/NodeUnpublish requests, only one of them runs in parallel
=> Serialize NodePublish and NodeUnpublish

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, operator/controllers/config/constants.go
Bump CSI sidecar to following versions:
CSI Attacher -> 4.2.0 -> 4.3.0
CSI Provisioner -> 3.4.1 -> 3.5.0
CSI resizer -> 1.8.0
CSI Node Driver Registrar -> 2.8.0
```release-notes
```
-
-
=> Sidecar upgrade 2.10.0 release

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/nodeserver.go, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/api/v1/csiscaleoperator_types.go, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml, operator/controllers/config/constants.go, operator/controllers/csiscaleoperator_controller.go, operator/controllers/syncer/csi_node.go, operator/controllers/syncer/csi_syncer.go, operator/go.mod, operator/go.sum
```release-notes
```
- [ x] Build related changes
-
-
=> Build8sept

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
```release-notes
```
- [x ] Build related changes
-
-
=> Build changes for sep15th

operator/controllers/syncer/csi_syncer.go
=> Fix #985 :Increasing memory for sidecar to handle scaled workload

driver/csiplugin/controllerserver.go
Fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/1016
Co-authored-by: Deepak R Ghuge <deeghuge@in.ibm.com>
If a fileset is created with non-zero quota which does not match the requested size in PVC, then CSI driver gives error and doesn't try to set quota
If a fileset is created with some quota which does not match the requested size in PVC, then CSI driver tries to set the correct quota
=> Fix CSI part for issue 1016

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
- [x ] Build related changes
-
-
=> CSI 2.10 RC1 Build

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
```
- [ x] Build related changes
-
-
=> updating dev branch with latest images

tools/generate_static_provisioning_yamls.sh
=> generate_static_provisioning_yamls.sh usage improvement

operator/controllers/csiscaleoperator_controller.go
Fixes for the issues [CSO event shows UpdateFailed event during upgrade](https://github.com/IBM/ibm-spectrum-scale-csi/issues/935)
```release-notes
```
- In the current behaviour, there have been setup of some defaults which is not required. A failed CSO events being generated during upgrade and even on fresh installs.  
- We are removing this since this is not required.
=> removed setting defaults

driver/csiplugin/connectors/rest_v2.go
Fixes https://github.com/IBM/ibm-spectrum-scale-csi/issues/1054 and https://github.com/IBM/ibm-spectrum-scale-csi/issues/1055
- [ x] Bugfix
- GUI HA connection is not happening if the n/w policy is not allowed to primary GUI
- GUI HA connection will take to the GUI where n/w policy is applied to
- [ x] Small, isolated change
=> Fix for GUI HA if n/w policy is not applied to primary GUI

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> changes for CSI 2.10 GM Build

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, operator/config/manager/manager.yaml
=> Cloudpak changes for 2.10.0

driver/cmd/ibm-spectrum-scale-csi/main.go
=> Spectrum Scale Driver initialisation logging

driver/csiplugin/controllerserver.go
fixes #880 
```release-notes
```
-
-
=> return error if mountOptions are specified

operator/controllers/syncer/csi_node.go, operator/controllers/syncer/csi_syncer.go
This PR will address the issue [https://github.com/IBM/ibm-spectrum-scale-csi/issues/1035](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1035)
```release-notes
```
-
-
=> annotation fixes on resources

driver/csiplugin/controllerserver.go
To fix issue [https://github.com/IBM/ibm-spectrum-scale-csi/issues/939](https://github.com/IBM/ibm-spectrum-scale-csi/issues/939)
```release-notes
```
-
-
=> delete symlink on manual fileset delete

driver/csiplugin/nodeserver.go, driver/csiplugin/utils/utils.go
To fix issue : [https://github.com/IBM/ibm-spectrum-scale-csi/issues/996](https://github.com/IBM/ibm-spectrum-scale-csi/issues/996)
```release-notes
```
-
-
=> fixes statfs call when volume mounted with symlink

driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go
```release-notes
```
- In the current implementation, the total time required to create multiple pvcs are much more like 14-15min for 100PVCs. 
- Some of the code refactoring changes have been done and same gui rest were called on Create request, that apis were restricted to be called once to minimise time. 
Dev test cases validated on time required for multiple pvcs creation with older image, and with this PR image. For validation, comparison would be easier if compared with 100+ pvcs.
=> volume create time optimisation

operator/controllers/csiscaleoperator_controller.go, operator/controllers/syncer/csi_node.go, operator/controllers/syncer/csi_syncer.go
=> reconcile issue on annotation updates

driver/cmd/ibm-spectrum-scale-csi/main.go
=> gosec fix on filepath

driver/csiplugin/nodeserver.go
=> fix pod termination issue when kubelet mounted as symlink

driver/cmd/ibm-spectrum-scale-csi/main.go, driver/csiplugin/gpfs.go
=> changes related to logs to remove password

driver/csiplugin/controllerserver.go
```release-notes
```
-
- Changes related to removal of mounting checks on the gui nodes before volume_provisioning. Those are not required, if the mount is not present then error comes as part of response. so unnecessary checks not required.
=> removed unnecessary gui mount fs checks

operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go
```release-notes
CSI Attacher -> 4.5.0 -> 4.5.1
CSI Provisioner -> 4.0.0 -> 4.0.1
CSI resizer -> 1.10.0  -> 1.10.1
CSI Node Driver Registrar -> 2.10.0 -> 2.10.1
CSI snapshotter -> 7.0.1 -> 7.0.2
```
-
-
=> sidecar upgrade for CSI 2.12.0

driver/build/Dockerfile
=> UBI9 change 

operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go, operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go
CSI Attacher -> 4.5.1 -> 4.6.2
CSI resizer -> 1.10.1 -> 1.11.1
CSI snapshotter -> 7.0.2 -> 8.0.1
Operator Image: [quay.io/shrutika_nipane/ibm-spectrum-scale-test:sidecars2](http://quay.io/shrutika_nipane/ibm-spectrum-scale-test:sidecars2)
-
-
=> Updates for external sidecars

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
=> UBI Lockdown and version change CSI 2.10.3

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> update 2.10.3 driver and operator shas after UBI lockdown

driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/resources.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/utils.go
Fixes for:
* PVC goes to bound even without gateway - scale-core#7086
* Intermediate error while creating cache volume - scale-core#7168
* Masking of keys - scale-core#7094
* Multiple PVCs getting created with AWS bucket - scale-core#7200
* Fix parallel cache volume creation - scale-core#7207
=> AFM cache fixes

driver/cmd/ibm-spectrum-scale-csi/main.go, driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/resources.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/settings/scale_config.go, driver/csiplugin/utils.go, driver/csiplugin/utils/http_utils.go, driver/csiplugin/utils/utils.go
AFM cache volume fixes for:
- Delete bucket keys in volume deletion flow. **Note: This requires Scale 5.2.1 on storage cluster** (If you are using Scale 5.2.1 dev build, make sure to use the build from 4th July or later)
- Use SSL option by default if endpoint is https
- Remaining pieces of keys masking
=> AFM cache volume fixes

driver/cmd/ibm-spectrum-scale-csi/main.go, driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/resources.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/settings/scale_config.go, driver/csiplugin/utils.go, driver/csiplugin/utils/http_utils.go, driver/csiplugin/utils/utils.go, driver/examples/cacheVolume/pvc.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Merge from dev to release-2.12
=> Release 2.12

tools/storage-scale-driver-snap.sh
```release-notes
```
- previous parameter was not collect previous logs from csi pods
- previous logs will be collected from pods
=> adding previous parameter in csi snap

operator/config/overlays/cnsa-k8s/kustomization.yaml
=> kustomize changes for k8s

operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go, operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go
CSI Provisioner -> 4.0.1 -> 5.0.2
-
-
=> Provisioner update to v5.0.2

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/default/kustomization.yaml
=> change to quay prod (#1197)

driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
```release-notes
sidecar upgrade for CSI 2.13.0 & version change
csi-resizer   ->   v1.11.2     
csi-node-driver-registrar  -> v2.11.1     
livenessprobe   ->   v2.13.1    
```
-
-
=> sidecar upgrade for CSI 2.13.0 & version change

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
CSI images update after merging #1202 
-
-
=> [dev] Update CSI images after UBI unlock

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/manager/manager.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/controllers/config/constants.go
CSI Snapshotter -> 8.0.1 -> 8.1.0
LivenessProbe -> 2.13.1 -> 2.14.0
-
-
=> Updating snapshotter sidecar and livenessprobe

driver/csiplugin/controllerserver.go, operator/controllers/csiscaleoperator_controller.go
```release-notes
```
This PR is going to fix the issue [Fileset should not be deleted if fileset is not created by CSI](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1188)
-
-
=> Restrict fileset deletion for non-csi created filesets

driver/build/Dockerfile
=> lock down driver ubi-minimal for CSI 2.13 (#1220)

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updating CSI driver image after locking it down with [ubi:9.4-1214.1726694543](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview)
=> [release-2.13] Update driver sha

driver/csiplugin/controllerserver.go
---------
```release-notes
```
-
-
=> fixed issue of not to create temp dir for ro mode (#1225)

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> [release-2.10] Update driver and operator shas after 2.10.5 update

operator/config/manager/manager.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml
We plan to change the icr location for the next release, dev. 
```release-notes
none
```
- ICR path is `spectrum/scale` 
- ICR path is `gpfs`
=> rename icr path from spectrum/scale to gpfs

driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/overlays/default/kustomization.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
CSI version change to `2.13.1` and UBI-minimal lockdown to `9.5-1731593028`
=> [release-2.13] changes for 2.13.1 and UBI lockdown

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/overlays/default/kustomization.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
CSI version change to `2.10.5` and UBI-minimal lockdown to `9.5-1731593028`
=> [release-2.10] changes for 2.10.6 and UBI lockdown

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> [release-2.10] update CSI driver and operator digests

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> [release-2.13] update CSI driver and operator digests

operator/controllers/csiscaleoperator_controller.go
=> updated to handle reconcile issue when openshift secrets are being auto populated

driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go
=> cherry pick the unlink fset changes in release 2.13

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> update sha's for 2.10.6

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's digest after PR #1275 was merged.
=> [release-2.13] update driver sha after UBI bump

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's digest after PR #1276 was merged.
=> [release-2.10] update driver sha after UBI bump

driver/csiplugin/controllerserver.go
```release-notes
```
This PR will address this issue [https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8119](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8119)
-
-
=> added check when fileset not present in delete volume

driver/csiplugin/controllerserver.go
=> cherry pick pr 1281 for release-2.13.1

driver/csiplugin/controllerserver.go
=> Release210 cherrypick  for release-2.10.7

driver/csiplugin/controllerserver.go
The message in attach failure is ambiguous so fixing the same
```release-notes
```
-
-
=> fixing message in Attach Operation

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml, cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/overlays/default/kustomization.yaml, operator/controllers/config/constants.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
CSI version change to `2.10.7` and UBI-minimal lockdown to `9.5-1739420147`
=> [release-2.10] changes for 2.10.7 and UBI update

driver/csiplugin/controllerserver.go
=> changes to validate quota is enforced or not and filesetdfenabled error log changes

.travis.yml
=> arm64 support

driver/csiplugin/connectors/connectors.go, driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs_util.go
This PR is going to handle issue [afm cache volume Pod is getting attached when filesystem is not mounted on gateway node](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/7175)
```release-notes
```
-
-
=> changes to address the issue when fs is not mounted on gateway nodes

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> changes for 2.14 Apr2nd Build

driver/csiplugin/controllerserver.go
=> changing comment for cg independent filesets

driver/csiplugin/connectors/connectors.go, driver/csiplugin/controllerserver.go, driver/csiplugin/gpfs_util.go, driver/examples/staticVolume/dynamicprovisioning/volume/storageclass_static_dependent.yaml, driver/examples/staticVolume/dynamicprovisioning/volume/storageclass_static_expansion_independent.yaml, driver/examples/staticVolume/dynamicprovisioning/volume/storageclass_static_independent.yaml
=> update existingData to existingVolume for staticPV

driver/csiplugin/controllerserver.go, operator/controllers/csiscaleoperator_controller.go
Primary fset is not shown in local gui once it is created by csi operator, so pvc provsioning fails.
=> changes for primary fset link issue

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
=> changes for CSI 2.14 GM Build

.travis.yml, driver/build/Dockerfile, driver/cmd/ibm-spectrum-scale-csi/main.go, generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/Makefile, operator/build/Dockerfile, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/manifests/bases/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml, operator/controllers/config/constants.go, operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go, tools/ansible/common/dev-env.yaml, tools/ansible/common/runtime-env.yaml
=> ARM64 Support with 2.13.2

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
```release-notes
image sha update for 2.13.2
```
-
-
=> image sha update for 2.13.2

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's and operator digests after #1327 was merged.
=> [release-2.10] update shas for CSI operator and driver (v2.10.8)

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's and operator digests after #1333 was merged.
=> [release-2.14] update shas for CSI operator and driver (v2.14.1)

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's and operator digests after #1337 was merged.
=> [release-2.14] update shas for CSI operator and driver

driver/csiplugin/controllerserver.go
=> Issue_8955 refactor of the ControllerPublishVolume operation.

generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml, generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's and operator digests after #1352 was merged.
=> [release-2.10] update shas for CSI operator and driver (v2.10.9)

generated/installer/ibm-spectrum-scale-csi-operator.yaml, operator/config/overlays/cnsa-k8s/kustomization.yaml, operator/config/overlays/cnsa/kustomization.yaml, operator/config/overlays/default/kustomization.yaml
Updated the CSI driver's and operator digests after #1360 was merged.
=> [release-2.14] update shas for CSI operator and driver (v2.14.2)

operator/go.mod, operator/go.sum
=> updating operator with the updated driver with PR #1377

.travis.yml
=> travis image push error fixes

driver/csiplugin/connectors/rest_v2.go, driver/csiplugin/identityserver.go, driver/csiplugin/settings/scale_config.go, operator/controllers/csiscaleoperator_controller.go
=> Remove cacrt name restriction - Cherry_PR1377

tools/volume_migration_scripts/README.md, tools/volume_migration_scripts/README_migration_csi_to_cnsa.md, tools/volume_migration_scripts/migration_csi_to_cnsa.bash
=> updated migration script doc

tools/volume_migration_scripts/README.md, tools/volume_migration_scripts/README_migration_csi_to_cnsa.md, tools/volume_migration_scripts/migration_csi_to_cnsa.bash
=> cherrypick_PR 1389 - updated migration script doc (#1389)
