.travis-pub.yml
.travis.yml
README.operator.md
operator/build/Dockerfile
tools/ansible/generate-playbook.yaml
tools/scripts/ci/ci-env

```
[root@c943f4n01-pvt operator]# operator-sdk build csi-scale-operator
INFO[0005] Building OCI image csi-scale-operator
Sending build context to Docker daemon 43.92 MB
Step 1/8 : FROM quay.io/operator-framework/ansible-operator:v0.11.0
---> 9a7b807df8cf
Step 2/8 : MAINTAINER jdunham@us.ibm.com
---> Using cache
---> 5fc5eba820c8
Step 3/8 : LABEL name "IBM Spectrum Scale CSI Operator" vendor "ibm" version "1.0.1" release "1" run 'docker run ibm-spectrum-scale-csi-operator' summary "An Ansible based operator to run and manage the deployment of the IBM Spectrum Scale CSI Driver." description "An Ansible based operator to run and manage the deployment of the IBM Spectrum Scale CSI Driver."
---> Using cache
---> a540a1661b4c
Step 4/8 : COPY build/health_check.sh .
---> Using cache
---> …
```

Changes to build the operator manually and travisCI to pass in operator piece.

---

operator/molecule/default/tests/basic_tests.yaml
operator/molecule/default/tests/test_creation.yaml
operator/roles/csi-scale/tasks/cluster_check.yml
operator/roles/csi-scale/tasks/main.yml

Resolves #42. 
- Refined the operator plays to  skip secret checks on delete.
- Improved operator plays  handle invalid secrets more correctly (old logic was faulty).
- Adds a test to create a custom resource without a valid secret.

Fix for invalid secrets hanging create/delete of Custom Resources

---

operator/roles/csi-scale/defaults/main.yml

Bumps the default version of  the driver  in the operator defaults (won't pass until driver is in  quay).

Bumping default to 1.0.1

---

.golangci.yml

Sometimes on a slow machine golangci-lint might error due to passing the timeout of 1 minute.  This is mostly for CI/CD that it might be an issue

Bump golangci-lint timeout from default of 1m to 3m

---

docs/source/get-started/prereq.rst

Resolves #68 
In operatorhub.io, the operator is deployed into a namespace called "my-ibm-spectrum..."  
To help avoid confusion, mimic the user/pass format above in that document page, and force the user to set the OPERATOR_NAMESPACE variable by defaulting to "SomeNamespace", which should indicate an invalid namespace.

Avoid confusion by forcing the user to set an OPERATOR_NAMESPACE variable

---

operator/build/multi-arch.Dockerfile
operator/roles/csi-scale/defaults/main.yml

```release-notes
add ARG's for image overrides in multi-arch Dockerfile, so CI/CD can bake nightly operator that defaults to nightly driver
add ENV's for image overrides in operator image, so testers may override image defaults by adding container env in the operator deployment
```

[WIP] depends on #66 - override image defaults with ENV variables

---

tools/spectrum-scale-driver-snap.sh

Fixes #111 
- Changed default snap namespace to ibm-spectrum-scal-csi-driver
- Fix to collect logs even if driver is not running

snap changes

---

driver/examples/dynamic/fileset/storageclassfileset_dependent.yaml
driver/examples/static/static_pv.yaml
tools/generate_pv_yaml.sh

Fixes #133 
Fixed Provisioner name in the examples and generate_pv.yaml
Fixed parent fileset name to avoid confusion.

Fix provisioner name in examples 

---

README.md
operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.1.0/ibm-spectrum-scale-csi-operator.v1.1.0.clusterserviceversion.yaml
operator/roles/csi-scale/templates/cluster-role-attacher.yaml.j2

Closes #145 
The attacher cluster role was missing the `csinodes` resource rules.

Attacher Fix for Remote FS

---

tools/spectrum-scale-driver-snap.sh

Fixing a problem  with how the snapshotting tool handles operators provisioned with OLM. Discovered when debugging a snapshot.
@gandhisanjayv  @Jainbrt - It looks like the  snapshot tool doesn't gather on olm, do we have any test automation  to verify all the  files  are created?

Snapshotting tool fails to process olm operators.

---

.travis.yml
driver/build/Dockerfile
operator/build/Dockerfile

Fixes #152. Adds a `git_commit` label  to the image tags for both the operator and driver images.

Adding git commit label to image labels

---

driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

fixes #16 
clusterId is optional in storageClass
if not specified Primary clusterId will be used to create volumes.

make clusterId optional in storageClass

---

driver/licenses/apache-2.txt

The operator image is correct because it is not symlinking it's license file.  (operator docker build context is ./operator)
The driver image is incorrect because it is symlinking to a license file outside it's build context.  (driver docker build context is ./driver)
- Fix is to not symlink.  Alternatively, we could change the build context to project root.

driver doesn't include correct license file, due to symlinking outside build context

---

driver/csiplugin/controllerserver.go

Check if primary fileset is linked before volume creation, fail if not linked
- Volume creation must fail with proper error when Primary fileset is not linked
No Required
NA
Fixes #157

Checking primary fileset state before volume create

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

Filesystem type check before creating fileset based volume. 
Create storage class with remote filesystem without cluster id, it should fail with proper error
NA
NA 
fixes #182

Add check for filesystem type before creating fileset

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/resources.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs.go

Check if Primary filesystem is mount on GUI before creating fileset in initialisation and volume creation
Following checks are added 
1.During initialisation 
- Primary filesystem is mounted on Primary Cluster GUI
- Primary filesystem is mounted on Remote Cluster GUI
2. During volume Creation 
- Primary Filesystem is mounted on Primary cluster GUI
- Volume filesystem is mounted on Primary cluster GUI
- Volume filesystem is mounted on Remote Cluster GUI if volume type is fileset and volume filesystem is remotely mounted
- Try CSI Driver deployment with primary fs unmount on GUI(single cluster + remote cluster setup)
- Try CSI Driver deployment with primary fs mounted on GUI((single cluster + remote cluster setup))
- Try volume creation when primary filesystem unmounted on GUI node
- Try …

Verify Primary fs is mounted on GUI node during initialisation and volume creation

---

.travis.yml
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

Create Volume idempotency changes
- If rest calls fails, clean will not happen instead when k8s request again volume creation will continue considering previous command failed at some point.
**CreateVolume**
* Request validation
* Parameter validation
* Validate if primary fileset is linked
* Validate if primary filesystem and/or volume filesystem is mounted on GUI node
* If fileset based volume 
- Check if filesystem is mounted on gui of remote cluster
- Check if quota is enabled for filesystem
- Check if fileset is present if not create it, 
- Check if fileset is linked if not link it,
- Check if quota is set if not set quota, 
- Check if  pvc-data directory is present if not create it
* If lw based volume 
- Check if base directory is present, if not return error
- Check if lw …

Idempotency - CreateVolume 

---

operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/2.0.1/ibm-spectrum-scale-csi-operator.v2.0.1.clusterserviceversion.yaml

Added the following CSV labels:
```
operatorframework.io/arch.ppc64le: supported 
operatorframework.io/arch.s390x: supported
operatorframework.io/arch.ppc64le: supported
```

Operator Framework labelling

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/resources.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

Added check if the Spectrum Scale cluster supports snapshotCopy operations. These operations are supported in Scale version 5.0.5.2 or later.
For this check, we query the REST info endpoint which returns GUI server information like Spectrum Scale version and also lists all the endpoints supported by that version.

Check Scale cluster supports for snapshotCopy operation

---

SNAPSHOTS.md
driver/csiplugin/controllerserver.go

Source fileset quota is used as snapshot restore size instead of block usage.

Using source fileset quota as snapshot restore size.

---

operator/roles/csi-scale/templates/csi-plugin.yaml.j2
operator/roles/csi-scale/templates/scc.yaml.j2

Hi, 
I was wondering if hostNetwork is truly need for the CSI plugin pods.  It seems that CSI driver plugin is not listening on hostNetwork and this is not needed.  
If hostNetwork actually is required for some reason that I do not see, then it would be good to use `dnsPolicy: ClusterFirstWithHostNet` so that the CSI pods can properly resolve cluster services.
Thoughts?

do not use hostNetwork for CSI pods

---

operator/build/Dockerfile

bumping ansible-operator version to v0.19.4

bumping ansible-operator version to v0.19.4

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/resources.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

The snapshot creation timestamp returned by Spectrum Scale REST API does not contain timezone info. Enhanced the code to get timezone offset from cluster config REST API to construct the correct creation timestamp.

Fix snapshot creation timestamp

---

driver/csiplugin/controllerserver.go

If inodeLimit is not specified in StorageClasss then use following formula to calculate the inodeLimit instead of using default 1million. 
inodeLimit = PV size / Filesystem Block size
Fixes #321

dynamic inode limit calculation

---

operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml
operator/roles/csi-scale/defaults/main.yml
operator/roles/csi-scale/templates/cluster-role-attacher.yaml.j2
operator/roles/csi-scale/templates/cluster-role-provisioner.yaml.j2

- Upgraded to newer sidecar images
- Added required access to the attacher and provisioner clusterroles
- Used gcr images as defaults
- Updated the CR file to point to gcr images
Documentation impact:
Doc needs to be updated to point to new images

Upgraded sidecars and using gcr images as defaults

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/gpfs.go

Executing fileset refresh task during plugin init  if the file system is remotely mounted. This is so that the fileset is visible in local/primary cluster's GUI

Executing fileset refresh task during plugin init 

---

SNAPSHOTS.md
operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml
operator/roles/csi-scale/defaults/main.yml
operator/roles/csi-scale/templates/cluster-role-snapshotter.yaml.j2
operator/roles/csi-scale/templates/csi-plugin-snapshotter.yaml.j2
tools/scripts/ci/install_minikube.sh

Changes :
1. Change for using csi-snapshotter 4.0.0 version for snapshot sidecar 
2. Changes in snapshots.md for using minimum OCP 4.7 for snapshot use
3. Removed secret permission from snapshot cluster role as it is not required in our CSI driver 
More details here :
https://github.com/kubernetes-csi/external-snapshotter/blob/release-4.0/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
4. Make changes for travis CI to run (removed CPU requirement from minikube)
5. Made changes in args for csisnapshot sidecar according to https://github.com/kubernetes-csi/external-snapshotter/blob/release-4.0/deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml#L91

changes for csi-snapshotter 4.0.0 version

---

driver/csiplugin/controllerserver.go

Added validation in ControllerPublishVolume for target path to check if it is a GPFS path. Should be tested with static provisioning.

Volume target path validation 

---

driver/csiplugin/nodeserver.go

k8s stopped creating the mount dir starting k8s 1.20. 
Driver was failing to mount due to error in removing the non-existent directory
**Change :** 
- Delete the Dir/Symlink on NodePublish call
- Replaced rmdir with go native remove
- replaced ln with go native function
- use Remove instead of RemoveAll in NodeUnpublish
Test suggestion : 
- try on k8s 1.20 and 1.19
- try creating application pod with pvc
- try rebooting the node where app pod is running
- try rebooting the GUI node of CNSA where app pod is also running
closes #384

NodePublish fix for handling mount dir behaviour change in k8s 1.20

---

driver/csiplugin/controllerserver.go

Handle mmxcp abort case such that copy snapshot is attempted again in the next k8s retry cycle

Handle driver pod restart case while snapshot restore is in progress

---

tools/ansible/k8s-olm-test-playbook.yaml
tools/ansible/oc-olm-test-playbook.yaml
tools/ansible/olmupgrade.md
tools/spectrum-scale-driver-snap.sh

1. Fix for clusterroles and clusterrolebindings
2. added support for 2.2.0 in olm upgrade automation and olm-catalog path

Changes in snap.sh and olm upgrade automation 

---

driver/csiplugin/connectors/rest_v2.go

curretly csi wait for 2 second for rechecking the job status.
This wait loop is infinite unless GUI timeouts which is usually 10 minutes
Now instead of waiting for 2 second everytime, wait time is doubled until reached to 16 second
Signed-off-by: Deepak R Ghuge <deeghuge@in.ibm.com>

increasing wait time exponentially instead of constant

---

driver/csiplugin/connectors/rest_v2.go

If set quota is set correctly in last attempt of volume creation then CSI driver must not retry set quota. 
Signed-off-by: Deepak R Ghuge <deeghuge@in.ibm.com>

fixing the listquota checks

---

driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

minimum volume size for fileset based volume to be 1GB
Allocated inode set to 1024

minimum volume size for fileset based volume to be 1GB

---

tests/functional-tests/utils/scale_operator_object_function.py

fix for extracting csi driver image name from pod in automation

fix for  extracting csi driver image name from pod

---

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
generated/installer/ibm-spectrum-scale-csi-operator.yaml
operator/config/manager/manager.yaml
operator/config/manifests/bases/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/2.3.0/ibm-spectrum-scale-csi-operator.v2.3.0.clusterserviceversion.yaml
operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/manifests/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml

This is a requirement for casebundle linting. And beta.kubernetes.io/arch got deprecated in k8s 1.18 also.
For kubernetes reference : 
https://github.com/kubernetes/kubernetes/pull/89462
beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18 #89462

replace affinity label from beta.kubernetes.io/arch to kubernetes.io/arch

---

driver/csiplugin/controllerserver.go

Quota does round up when requested quota is not multiple of filesystem block size
fixes #463

fix for quota round up

---

kustomization.yaml

In order to copy the manifests via URL, the directories in the Kustomization (manager, rbac and crd) must either be within the same directory as the Kustomization or in a subdirectory. In this PR I'm adding a copy of the kustomization.yaml to the config directory so that this can be used to pull the CSI manifests via URL.

Add a copy of the default Kustomization to the config dir

---

driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

```release-notes
```
Below defects:
1. Lost access to fileset and data if fileset is present with same name as namespace #579
2. PVC creation should fail saying storageclass parameter "type=advanced" and "filesetType: independent" can not be mutual (Issue #583)
Fixed for above mentioned defects

Fixes for defects #579 and #583

---

driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

```release-notes
```
Currently independent fileset for consistency group gets delete by CSI driver even if had not created it.
Independent fileset for consistency group won't get deleted by CSI driver if had not created it.

Fix for defect #580

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/resources.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

Compression will support the algos specified in 'File compression' in https://www.ibm.com/docs/en/spectrum-scale
Add replication/tiering support with defaulted replication values
```release-notes
Added support for compression/tiering/replication within a storageclass
```
- N/A
- With this change, a compression, tier, and replication values can be supplied in the storageclass spec.
Once a pvc is created, some validation checks will be done such as making sure a valid compression algorithm was specified or a valid range for replication was set. For tiering and replication, a new rule will be set in the filesystem policy so any new files will be placed/replicated accordingly.

Add compression/replication/tiering support for storageclass

---

driver/csiplugin/controllerserver.go

- Fix for issue https://github.com/IBM/ibm-spectrum-scale-csi/issues/572
- But there can be following issue with the same re-create steps, in some cases:
```
[EFSSG0763C The parent directory "/ibm/gpfs0/ibm-spectrum-scale-csi-driver" of the specified junction path does not exist.]
```
It is due to scale gui db sync issue (in some cases, the result of `mmunlinkfileset` run on scale cluster may not sync immediately on scale gui db), so it is recommended not to unlink any CSI fileset.
- Set uid and gid as 0 for CG independent fileset

Don't create directory for CG independent fileset

---

driver/csiplugin/controllerserver.go

```release-notes
```
Volume cloning fails for CG after removing -data directory
Volume cloning passes for CG after removing -data directory

Fix for volume cloning for consistency group

---

driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

setting inodeLimit to 1M for consistencyGroup is user has not specified the inodeLimit in storageClass
adding validation for compression=false
```release-notes
```
fixes #596 
fixes #591 
-
-

setting inodeLimit to 1M for consistencyGroup

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/gpfs_util.go

- Change storage class parameter `type` (which had value `advanced`) to `version` which can have values 1 (for old storage class) or 2 (for new storage class)
- Some changes to parameters allowed with storage class with version 2:
* Allow parameter `inodeLimit`
* Disallow parameter `parentFileset`
Some code readability enhancements TODO later:
* Use `version` instead of `type` everywhere for CG
* Change volume handle <storageclass_type> value to 1 or 2(which is currently 0 or 1), to be consistent with `version` value
```release-notes
```
-
-

Change `type` SC parameter to `version`

---

driver/csiplugin/controllerserver.go

Fixes https://github.com/IBM/ibm-spectrum-scale-csi/issues/606
Fixes #610 
```release-notes
```
- For "version": "2" with remote cluster filesystem, pod is unable to attach pvc
- volumes are now attached to pod.

Fix for issue 606  and 610

---

driver/csiplugin/controllerserver.go

When checking filesystem version to enable tiering,
if the CNSA/Primary connection output is not at least
2700 version, we will fallback and query the remote
GUI for the filesystem version. CNSA/Primary connection
might have outdated cache data.
```release-notes
```
The CNSA gui pod may have cached filesystem version info. Especially if the fs version was upgraded. Since the volfsInfo contains that data it could be outdated for up to a day.
The new behavior is to first check if the CNSA data is downlevel, and if so try the remote storage gui directly. If both show downlevel fs version then we are for sure down level. Otherwise if the remote storage gui is showing the correct level then we know it was cached but we can continue with the …

Check FS version on both  remote/local gui

---

operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

- Fixes #625 
- Tolerations are not set correctly in driver and controller pods because of which pods were scheduling only to worker nodes.
- Removed the duplicate logic of adding tolerations in pod template, duplicate logic was updating tolerations in incorrect format.

Removed duplicate toleration logic

---

driver/csiplugin/controllerserver.go

```release-notes
```
Independent fileset for CG doesn't get deleted if all PVCs are deleted first and then all snapshots are deleted.
Fix for - Independent fileset for CG doesn't get deleted if all PVCs are deleted first and then all snapshots are deleted.

Fix for issue #620 and added fix for snapshot restore of a PVC after PVC got deleted 

---

driver/csiplugin/controllerserver.go
generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
generated/installer/ibm-spectrum-scale-csi-operator.yaml
operator/config/rbac/service_account.yaml
operator/controllers/config/constants.go
operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

- Code changes for part 1 of https://github.com/IBM/ibm-spectrum-scale-csi/issues/632
* Add ibm-entitlement-key as another default image pull secret
* Keep default pull secrets even when user specifies the pull secrets
* Removed duplicate setting of pull secrets 
- Part 2 (check for pull failures and include a message to the user for debug) is WIP - The state of pods changes from ImagePullBackOff to CrashLoopBackOff to ImagePullErr - so the pull error is logged only sometimes currently - will create a separate PR for this.
```release-notes
```
-
-

Add `ibm-entitlement-key` as default image pull secret

---

driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

- Set permissions for dependent fileset, if passed from version 2 SC
Permissions do not get set to dependent fileset directory for version 2 SC
Permissions are set to dependent fileset directory for version 2 SC

Fix permissions for version 2 SC

---

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
operator/api/v1/csiscaleoperator_types.go
operator/config/manifests/bases/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/2.5.0/ibm-spectrum-scale-csi-operator.v2.5.0.clusterserviceversion.yaml
operator/config/olm-catalog/ibm-spectrum-scale-csi-operator/manifests/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
operator/docs/dev/security/results.golint.txt
operator/docs/dev/security/results.gosec.json

- In OCP UI, Consistency Group Prefix is set as visible and available for user to modify.
- Consistency Group Prefix is set as hidden by default.
- Since consistency group prefix is fetched from the cluster, users don't need to explicitly provide a input for this unless they want to modify it.

consistencyGroupPrefix is set as hidden in OCP UI

---

operator/controllers/internal/csiscaleoperator/csiscaleoperator.go
operator/controllers/syncer/csi_node.go

```release-notes
Fix systemd high load with recursive mount
```
- If driver container is in crash loop backoff, bidirectional mount combined with a mount of a subdir eats up `mountinfo` under `systemd`. This cause extremely high CPU utilization and eventually leads to the node being unusable.
- Only mount `/var/lib/kubelet` rather than both `/var/lib/kubelet` and `/var/lib/kubelet/plugins/spectrumscale.csi.ibm.com`
- I believe the driver container will fail in crash loop until another container creates the `/var/lib/kubelet/plugins/spectrumscale.csi.ibm.com` directory. This a future improvement that could be done here.

Fix systemd high load with recursive mount

---

operator/controllers/internal/csiscaleoperator/csiscaleoperator_package.go

* Remove duplicate node affinity blocks
* Add affinity passed from CR to driver pods too
* Note: Though arch based node affinity (or any node affinity) is added for driver pods (this is not visible in pod spec, because of getting scheduled by a daemonset, and node affinity being overwritten by the daemonset, the arch based affinity will be used by k8s to decide on which nodes daemonet pods should be run, otherwise by default daemonset pods will be scheduled on all worker nodes in the cluster)

Fix node affinity

---

operator/config/overlays/ocp-rhel/security_context_constraint.yaml

* Add a separate SCC file having service account namespace `ibm-spectrum-scale-csi-driver` for OLM install.
* Note: this file doesn't impact current kustomization overlay, it is  only for OLM install documentation. It will be removed in 2.7.0 along with OLM support.

Add a separate SCC file for OCP RHEL

---

driver/csiplugin/gpfs.go
driver/csiplugin/nodeserver.go
driver/csiplugin/utils/utils.go

When Volume is Attached to Running pod, The PersistentVolumeClaims panel on OpenShift UI shows used size under **Used** column. 
- The Used size is only visible for Fileset based volume
- The Used size is not visible for lightweight based volume since we don't have quota on it 
The logs will show `volume stat not supported for lightweight volumes` for lightweight based volumes
```release-notes
```
-
-

volume stat support

---

driver/csiplugin/nodeserver.go

* Before mounting a volume, check whether the path is of type "gpfs"
* Fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/761 ()
- Any path gets mounted inside a pod.
- Only the path of type "gpfs" can be mounted inside a pod.

Fix PV mounting

---

operator/controllers/config/constants.go

Switch to the new endpoint for container images. See: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
```release-notes
```
-
- Switch to the new endpoint for container images. See: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)

use registry.k8s.io for sidecar deployment

---

operator/controllers/syncer/csi_syncer.go

Increase the provisioner timeout to from 2m to 3m, as large number of PVC create and delete operation, volume provisioning is timing out and going beyond 2 minute
```release-notes
```
-
-

Increase the provisioner timeout to from 2m to 3m

---

driver/csiplugin/nodeserver.go
go.work.sum

Missing isNotFound error handling and less logs in NodePublish and NodeUnpublish
Adding isNotFound error handling and more/better logs in NodePublish and NodeUnpublish

Improve node publish and unpublish as per 2.7.0 fixpack changes

---

driver/csiplugin/gpfs.go
operator/controllers/csiscaleoperator_controller.go

-  Fix for upgrade path
- https://github.com/IBM/ibm-spectrum-scale-csi/issues/898 and 
- https://github.com/IBM/ibm-spectrum-scale-csi/issues/873
- Operator sets default primary fileset in 1st pass, which causes inconsistency between the CRs of CSI 2.8.0 and 2.9.0. For upgrade case (which is not a 1st pass) - operator does not set default primary fileset if it is empty in CR, which leads to an incorrect fileset/path for volume creation
Operator now does not update CR with the default primary fileset when primary fileset is empty in CR, instead driver sets default primary fileset to avoid upgrade path failures.

Fix upgrade path

---

operator/controllers/csiscaleoperator_controller.go
operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

- Fixing unnecessary driver pods restarts - https://github.com/IBM/ibm-spectrum-scale-csi/issues/926
- For the 1st volume operation after the optional configmap is updated, sidecars may still restart as sidecar pods may come up with a connection to socket of the old driver pod  before driver pod creates a new socket
- Unnecessary driver pod restarts
- Driver pods don't restart on volume operation

Fix pod restarts

---

operator/controllers/syncer/csi_node.go

- Set preStop hook (to delete the socket file) in CSI driver container instead of driver-registrar
- Fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/924
- Partial fix for https://github.com/IBM/ibm-spectrum-scale-csi/issues/864
preStop hook is present in driver-registrar container, which fails due to absence of shell
preStop hook is moved to csi driver container

Fix preStop

---

operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

CSI driver pod and Attacher pod should be drained after all application pods since unmount/detach operation has to succeed

adding PriorityClass to driver pod and attacher

---

driver/csiplugin/connectors/rest_v2.go
operator/controllers/csiscaleoperator_controller.go

- Fix whitespaces read from secret username and password
- Add more details like the URL, username, params, etc in error returned when REST call to GUI fails
- Whitespaces (including newlines) are not trimmed from username, newline at the end of password is not trimmed - which leads to authentication issue with GUI.
- If a REST call fails, operator does not have details about the called REST API.
- Whitespaces (including newlines) are trimmed from username, newline at the end of password is  trimmed. 
- If a REST call fails, operator will have the details about the called REST API after operator points to the driver once the PR is merged.

Fix whitespaces in secret credentials + add REST call info

---

driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/settings/scale_config.go
operator/controllers/config/constants.go
operator/controllers/csiscaleoperator_controller.go
operator/controllers/syncer/csi_node.go

* Dot in secret/cacert cm name causes problem with volume name in driver
* Wrong config in CSO causes operator to panic, see https://github.com/IBM/ibm-spectrum-scale-csi/issues/988
* Dot in secret/cacert cm name works fine, as we are now using `<cluster-id>-secret` as a volume name for secrets and `<cluster-id>-cacert` for cacert volume name
* Wrong config in CSO is handled fine, the issue will be actually fixed when operator points to the driver code after merging this PR.

Fix dot in secret/cacert and wrong config issue

---

operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

This is the PR for issue [Check on security settings](https://github.ibm.com/ibmspectrumscale/csi-tracker/issues/282)
```release-notes
```
The currently running pods/containers are not following recommended security specs. Some are running with priviledged and with root user. 
The new changes will restrict pods/containers to run explicitly with required permission where ever applicable. We have listed out all the changes into boxnote [Pod Security](https://ibm.ent.box.com/file/1233061703646).
Sheet-1 contains the running securityContext whereas Sheet-1(release-1.10) contains the latest changes of the secuityContexts.

changes for pod security-2.10

---

operator/api/v1/csiscaleoperator_types.go
operator/controllers/csiscaleoperator_controller.go

Zenhub Tracker: [Generate events for configmap parameter validation](https://github.ibm.com/IBMSpectrumScale/csi-tracker/issues/315)
```release-notes
```
- In the current behavior, there are no feature to show CSO events whenever any wrong data comes in the optional configMap.
- In the new behavior, there will have functionality to show CSO events in case of any wrong data comes in the optional configMap.

added events func in case of wrong optional cm data

---

driver/csiplugin/controllerserver.go

* For volume clone and restore, retry in case of copy job failure. 
Currently for volume clone or restore from snapshot, CSI driver doesn't retry if the copy job fails, and PVC stays in pending state forever
If the copy job fails, it will be retried
-

Improve volume cloning and restore

---

operator/controllers/syncer/csi_node.go

The fix has been provided for the Issue  regarding livenessprobe failing in the K8s and OCP+RHEL cluster: [Liveness probe failed error on OCP +RHEL worker nodes setup](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1033)
```release-notes
```
- The liveness-probe container showed intermittent timeout while calling GRPC call: /csi.v1.Identity/Probe to get health check. During the investigation, we have noticed that each requests are taking 1 to 5 seconds to get response for health check Probe.  
- To get fix, we are setting liveness-probe timeout to 20s from 1s(default), this will be used into Probe grpc call. The max wait time will 20sec before sending back response to the driver-kubelet liveliness call on /healthz http call.

added livenes-probe timeout

---

driver/csiplugin/controllerserver.go

While deleting a volume, skip checking for snapshots for dependent filesets
- CSI driver checks for snapshots for dependent filesets in volume deletion path
- CSI driver skips checking for snapshots for dependent filesets in volume deletion path

Skip checking for snapshots for dependent filesets

---

operator/controllers/config/constants.go
operator/controllers/csiscaleoperator_controller.go
operator/controllers/syncer/csi_node.go

Host network will always be enabled for driver pods
With current fix host network for driver pods is controlled by optional config map parameter "HOST_NETWORK". Default value will be ENABLED. If you DISABLED the parameter then host network for driver pods will be made false.

Fix for tunable network policy

---

operator/controllers/config/constants.go
operator/controllers/csiscaleoperator_controller.go
operator/controllers/syncer/csi_node.go
operator/controllers/syncer/csi_syncer.go

* Make CPU and Memory limits configurable for CSI driver containers and all the sidecar containers. 
* To configure CPU limits use the optional configmap with a key `DRIVER_CPU_LIMITS` , e.g. `DRIVER_CPU_LIMITS: 800m`
* Default CPU limit is `600m`
Default Limits are:
> DriverCPULimitsDefaultValue          = "600m"
DriverMemoryLimitsDefaultValue       = "600Mi"
SidecarCPULimitsDefaultValue         = "300m"
SidecarMemoryLimitsDefaultValue      = "800Mi"
CPU limits of the driver container is to `600m`. Other resources limits are the default values. 
CPU limits and Memory limits of the all the containers are configurable. 
There is a minimum value must be required to set. For CPU limit, minimum is 20m and for memory, minimum value is 20Mi. …

Make resources limits configurable for all the containers

---

operator/controllers/config/constants.go

```release-notes
Sidecar upgrade:
CSI Attacher -> 4.4.2 -> 4.5.0
CSI Provisioner -> 3.6.2 -> 4.0.0
CSI resizer -> 1.9.2  -> 1.10.0
CSI Node Driver Registrar -> 2.9.2 -> 2.10.0
CSI snapshotter -> 6.3.2 -> 7.0.1
New sidecar details:
registry.k8s.io/sig-storage/csi-snapshotter:v7.0.1
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
registry.k8s.io/sig-storage/csi-resizer:v1.10.0
registry.k8s.io/sig-storage/csi-provisioner:v4.0.0 
registry.k8s.io/sig-storage/csi-attacher:v4.5.0
registry.k8s.io/sig-storage/livenessprobe:v2.12.0
```
-
-

Sidecar upgrade for CSI 2.11.0

---

driver/csiplugin/connectors/rest_v2.go

[PV remains in terminating state with provisioner sidecar v5.0.1](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1173)
```release-notes
```
-
-

fixed for pv deletion issue with provisioner 501

---

driver/build/Dockerfile

We are currently building CSI driver with **UBI 9.4-949.1717074713** which is 3 months old. We want to be pulling the latest UBI tag available. Eventually when we get to DCUT phase, we'll want to cut a `release-2.13` branch and lock it down with the latest UBI tag available at that point in time. This way we can keep the UBI image in this `dev` branch alone and always pulling the latest UBI levels 😄 

unlock UBI minimal version for CSI driver

---

generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml
generated/installer/ibm-spectrum-scale-csi-operator.yaml
operator/config/manager/manager.yaml
operator/config/overlays/cnsa-k8s/kustomization.yaml

Provisioner images in the yaml files were pointing to old provisioner. 
Updating provisioner image to 5.0.2
-
-

Updating provisioner image in yamls

---

driver/build/Dockerfile

Now that `release-2.13` branch has been created, we need to lock down the ubi-minimal version used for the CSI driver image.
As of today, the latest ubi-minimal version available is [9.4-1227.1726694542](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?architecture=amd64&image=66eb4713df6256d9be473d28&container-tabs=overview)

[release-2.13] lock down ubi-minimal for CSI driver

---

driver/csiplugin/controllerserver.go

```release-notes
```
To handle issue [readonly cache volume PVC doesn't get created](https://github.com/IBM/ibm-spectrum-scale-csi/issues/1218)
- The tempdir shouldn't be created when modes are ro  cachemode
-
-

fixed issue of not to create temp dir for ro mode

---

driver/csiplugin/controllerserver.go

```release-notes
```
This will address the issue https://github.com/IBM/ibm-spectrum-scale-csi/issues/800
The max size supported by scale is 999999999999999K . The changes won't allow the user to create/resize more this allowed limit.
-
-

pvc size shouldn't more than scale allowed size

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

This PR  will handle the issue [CSI- Add gaurd rails around volume deletion to handle deadlock on volume delete](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8056)
```release-notes
```
-
-

added unlink fileset before the deletion of the fileset request

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

cherry pick the unlink fset changes in release 2.10.6

---

driver/build/Dockerfile

Need to update the UBI minimal tag in order for the CSI driver image to match the same UBI level used in CNSA 5.2.2.1

[release-2.13] update CSI driver's ubi-minimal tag

---

driver/build/Dockerfile

Need to update the UBI minimal tag in order for the CSI driver image to match the same UBI level used in CNSA 5.1.9.8

[release-2.10] update CSI driver's ubi-minimal tag

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

The feature request for this PR [Fileset created by csi needs to have namespace and pvc-name with comment](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8336)
- The current feature add a standard comment for the filesets created by csi as 
> "Fileset created by IBM Container Storage Interface driver"
- After this new changes, the fileset comment will have deatils of namepsace and pvcName in the standard comment for the filesets. 
e.g.
> "Fileset created by IBM Container Storage Interface driver for PVC [ scale-fset-pvc ] in the namespace [ ibm-spectrum-scale-csi-driver ]"

updated fileset comment with namespace and pvcname

---

driver/csiplugin/connectors/connectors.go
driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/controllerserver.go

This is to handle the issue where Independent fileset comment was wrong, as it took fileset name of the very first cg based fileset. 
```release-notes
```
- The independent fset created during the very first version-2 fset creation was being taken as fsetName during the comment of independentFset also.
- Every fileset will have their own fileset name in the comment.

fixed issue for comments for cg independent fileset

---

driver/csiplugin/controllerserver.go

Fix for vac validation parameters. Addresses below defects.
https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8370
https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8368 

Fix for vac validation and parameter values

---

driver/build/Dockerfile

Today we have entered mustfix phase for CNSA 5.2.3.0, which means we need to lock down the UBI images we will be using for this release.
Latest `ubi9-minimal` tag available as of today is [9.5-1742914212](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?image=67e2cfe11bae27c089d0d26c&gti-tabs=registry-tokens&container-tabs=gti)

lock down ubi9-minimal for CSI v2.14.0

---

cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/case.yaml
cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperator/resources.yaml
cloudpak/stable/ibm-spectrum-scale-csi-operator-bundle/case/ibm-spectrum-scale-csi-operator/inventory/ibmCSIScaleOperatorSetup/resources.yaml
driver/build/Dockerfile
driver/cmd/ibm-spectrum-scale-csi/main.go
generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
generated/installer/ibm-spectrum-scale-csi-operator-ocp-rhel.yaml
generated/installer/ibm-spectrum-scale-csi-operator.yaml
operator/Makefile
operator/build/Dockerfile
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
operator/config/manifests/bases/ibm-spectrum-scale-csi-operator.clusterserviceversion.yaml
operator/config/overlays/default/kustomization.yaml
operator/controllers/config/constants.go
tools/ansible/common/dev-env.yaml
tools/ansible/common/runtime-env.yaml

Getting ready for next CNSA release **5.1.9.10**
- CSI version change to `2.10.8`
- UBI-minimal lockdown to `9.5-1742914212`
- update quay path references to dev (`quay.io/ibm-spectrum-scale-dev`)

[release-2.10] changes for 2.10.8 and UBI update

---

driver/build/Dockerfile
driver/cmd/ibm-spectrum-scale-csi/main.go
generated/installer/ibm-spectrum-scale-csi-operator-dev.yaml
generated/installer/ibm-spectrum-scale-csi-operator.yaml
operator/Makefile
operator/build/Dockerfile
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
operator/config/overlays/default/kustomization.yaml
operator/controllers/config/constants.go
tools/ansible/common/dev-env.yaml
tools/ansible/common/runtime-env.yaml

Getting ready for next CNSA release **5.2.3.1**
- CSI version change to `2.14.1`
- UBI-minimal lockdown to `9.5-1745855087`
- update quay path references to dev (`quay.io/ibm-spectrum-scale-dev`)

[release-2.14] changes for 2.14.1 and UBI update

---

driver/build/Dockerfile

Updating ubi-minimal image to [9.6-1747218906](https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5?image=6824a0343e24a4f5ddfc6206&gti-tabs=registry-tokens&container-tabs=overview) for CSI driver in order to match the level for CNSA 5.2.3.1

[release-2.14] Update CSI driver to UBI 9.6 to match CNSA 5.2.3.1

---

driver/build/Dockerfile
driver/csiplugin/controllerserver.go
driver/csiplugin/gpfs_util.go

-This PR is going to handle the issue related to  : [attach volume should be successful even if the filesystem is mounted on 1 gateway node](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/7175)
```release-notes
```
- There was a strict check that filesystem should be mounted on all gateway node to create afm fileset 
- The afm fileset should get created even when the filesystem is mounted on any 1 gateway node

Fix for #7175 

---

driver/csiplugin/connectors/rest_v2.go
driver/csiplugin/gpfs.go
driver/csiplugin/identityserver.go
driver/csiplugin/settings/scale_config.go
operator/controllers/csiscaleoperator_controller.go

Handles Story: [[Story] Remove strict dependency on cacert data key and ConfigMap name for the CSI](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/9420)
PR to handle the issue raise during CNSA upgrade where csi failed to restart due to cacert issue.
[(EWM-349612) TS019318966 NSA Certification issues](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/8962)
There has been temporary solution provided by making sslMode as false(default) in the CNSA to pass.
[Change skip verify CNSA back to original default for cso](https://github.ibm.com/IBMSpectrumScale/scale-core/pull/9005)
- When secureSslMode is enabled in the CSO CR, CSI expects the CA certificate to be provided in a …

Removing dependencies on the cacert data key and certificate configMap name

---

driver/build/Dockerfile

UBI levels are being locked down for CNSA 6.0.0.0. This PR is to match the UBI levels between CNSA and CSI

[release-3.0] Lock down UBI minimal level for CSI driver

---

driver/csiplugin/controllerserver.go

Fixes: [symlink is not getting deleted when two filesystems are used](https://github.ibm.com/IBMSpectrumScale/scale-core/issues/9628)
```release-notes
```
-
-

adding fix for symlink delete error after primary removal
